### ISSUE TITLE
Unsupported fixup source: 12

### ISSUE THREAD

**Issue by claunia** [oshogbo/ghidra-lx-loader#11]
Hi,

Trying to decompile a Windows 9x VXD (LE format) I got this exception:
```
Unsupported fixup source: 12
java.lang.UnknownError: Unsupported fixup source: 12
	at lx.LXFixupRecordTable.<init>(LXFixupRecordTable.java:70)
	at lx.LX.loadFixupRecordTable(LX.java:104)
	at lx.LX.<init>(LX.java:126)
	at lx.LXLoader.load(LXLoader.java:142)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---------------------------------------------------
Build Date: 2021-Sep-09 1133 CEST
Ghidra Version: 10.0.3
Java Home: /usr/lib/jvm/java-11-openjdk
JVM Version: Oracle Corporation 11.0.12
OS: Linux 5.14.6-arch1-1 amd64
Workstation: localhost.localdomain
```

**Comment by madebr** [comment]
Can you share the VXD?

**Comment by goshhhy** [comment]
i am seeing similar errors depending on the VxD, but am so far unable to load any VxD i try. ("Unsupported fixup source: 13", "Unsupported target flags: 1", etc)

**Comment by oshogbo** [comment]
It would be useful for a link where to get VxD. I'm not familiar with this software.

**Comment by goshhhy** [comment]
you can find quite literally any windows 95 driver, including the ones included with windows 95. that's what a "VxD" is.

the specific one i am using is for the PowerVR PCX2. you can find several versions of it in these archives: https://github.com/powervr-graphics/PowerVR-Series1/tree/main/Documentation/sgl/Drivers/files

**Comment by madebr** [comment]
Opening `410c3deb` -> `vsgl.vxd` and `411c3deb.zip` -> `vsgl.vxd` from the link you posted,
I get the following error:
```
Unsupported target flags: 1
java.lang.UnknownError: Unsupported target flags: 1
	at lx.LXFixupRecordTable.<init>(LXFixupRecordTable.java:77)
...
```

This is a different error then OP is having.
"My" error is about missing support for import by ordinal number:
>     FLAGS = DB  Target Flags. 
>         The target flags specify how the target  information 
>         is interpreted.  The  target flags  are  defined  as 
>         follows: 
> 
>             03h = Fixup target type mask. 
>             00h = Internal reference. 
>             01h = Imported reference by ordinal.
>             02h = Imported reference by name. 
>             03h = Internal reference via entry table. 
>             04h = Additive Fixup Flag. 
>                 When set, an additive value trails the fixup 
>                 record (before the  optional  source  offset 
>                 list). 

As every VxD is linked differently, please provide one that uses a fixup source type of value 12.
