### ISSUE TITLE
Unsupported fixup source: 3

### ISSUE THREAD

**Issue by madebr** [oshogbo/ghidra-lx-loader#14]
Loading the 3dfx carmageddon executable fails with:
```
Unsupported fixup source: 3
java.lang.UnknownError: Unsupported fixup source: 3
	at lx.LXFixupRecordTable.<init>(LXFixupRecordTable.java:70)
	at lx.LX.loadFixupRecordTable(LX.java:104)
	at lx.LX.<init>(LX.java:126)
	at lx.LXLoader.load(LXLoader.java:142)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:724)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2022-Nov-01 1334 EDT
Ghidra Version: 10.2
Java Home: /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-2.fc36.x86_64
JVM Version: Red Hat, Inc. 17.0.5
OS: Linux 6.0.5-200.fc36.x86_64 amd64
Workstation: fedora
```
The executable `CARMAV.EXE` can be downloaded [here](https://rr2000.cwaboard.co.uk/R4/PC/3dfxROW.zip).

**Comment by madebr** [comment]
The fix-ups can be found in dos32-a's source code:
https://github.com/open-watcom/open-watcom-v2/blob/971128864befb698c695231d2c781e9b2b22f8a3/contrib/extender/dos32a/src/dos32a/loader.asm#L343-L418

**Comment by halamix2** [comment]
The same thing happens with the Pył (1998) game (Watcom C/C++, DOS/4GW)
