### ISSUE TITLE
'Unknwon file format: PE' Error

### ISSUE THREAD

**Issue by ElijahBI** [oshogbo/ghidra-lx-loader#8]
I was attempting to look at a file which I believe is LX, however it is responding with the error below. Do you think you could offer some assistance as to how I can move forward in getting this file open?

```
Unknwon file format: PE
java.lang.UnknownError: Unknwon file format: PE
	at lx.LXHeader.<init>(LXHeader.java:130)
	at lx.LX.<init>(LX.java:116)
	at lx.LXLoader.load(LXLoader.java:66)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by oshogbo** [comment]
Is it a PE binary or clear LX file?

**Comment by ElijahBI** [comment]
I am pretty sure it is a PE, though am just now getting started with all of this so I could be mistaken...

**Comment by oshogbo** [comment]
Can you share the binary?

**Comment by ElijahBI** [comment]
Hey, sorry for the late response. Here is a link to the exe [https://mega.nz/file/d1tllYhD#ikIKonxGx8XJ4dzVG2qB0_W0e2woRtSIFeQO9NjqCYI](url)

**Comment by oshogbo** [comment]
This binary worked for me.
![2021-05-22-214930_708x465_scrot](https://user-images.githubusercontent.com/673352/119239178-b6dde680-bb47-11eb-98af-58ac3b630165.png)
![2021-05-22-214937_787x827_scrot](https://user-images.githubusercontent.com/673352/119239180-b9d8d700-bb47-11eb-9f0a-383e5eaae346.png)

Did you import the plugin?
Did you build plugin by yourself or did you use one of the releases?
Which version of ghidra are you using?

**Comment by oshogbo** [comment]
Can you try this build https://github.com/oshogbo/ghidra-lx-loader/releases/tag/1.4 with the ghidra 9.2.3?

**Comment by ElijahBI** [comment]
I am still having issues an am unsure as to why exactly...

I have tried the 9.2 and 9.2.3 release builds now (with their respective versions of ghidra)

Here are some screen grabs:
9.2.3
![9 2 3](https://user-images.githubusercontent.com/83904099/119247066-661cbc80-bb4c-11eb-853c-b3a1f0d896d9.png)
Import options
![9 2 3 2](https://user-images.githubusercontent.com/83904099/119247069-687f1680-bb4c-11eb-836c-d882b69e2f88.png)
9.2
![a9 2](https://user-images.githubusercontent.com/83904099/119247073-6ddc6100-bb4c-11eb-9cae-78abdb71897d.png)
Import options
![a9 2 2](https://user-images.githubusercontent.com/83904099/119247075-703ebb00-bb4c-11eb-9ffd-eee1492f3513.png)

I'm extracting the zips to 'ghidra root\Ghidra\Extensions' and then checking in the 'install extensions' screen to see that they are indeed installed. Sorry if I am missing something simple here, it seems like you should be able to just pop this in and go...

One thing I did note: when I extracted your 9.2.3 build into my ghidra 9.2.3 install it would not start up the application until I renamed the folder from LX2 to LX. I kept getting a "Exited with error" message

**Comment by oshogbo** [comment]
You don't have to extract it.
This scenario works for me:
![2021-05-23-164217_700x593_scrot](https://user-images.githubusercontent.com/673352/119265095-c90e6200-bbe5-11eb-9a76-02ed3ddb8f18.png)

Click plus in the right top corner.

![2021-05-23-164323_791x546_scrot](https://user-images.githubusercontent.com/673352/119265133-ecd1a800-bbe5-11eb-840a-6f0ddf275f64.png)
Select the Extension.

![2021-05-23-164348_697x592_scrot](https://user-images.githubusercontent.com/673352/119265149-fbb85a80-bbe5-11eb-9349-12fe45dc0c6e.png)
Click ok.

![2021-05-23-164415_410x48_scrot](https://user-images.githubusercontent.com/673352/119265166-096de000-bbe6-11eb-8b08-d8b30ed59938.png)
Restart ghidra.

And you should get the Portable Executable (PE) with the LE:32. 
![2021-05-23-164536_496x208_scrot](https://user-images.githubusercontent.com/673352/119265288-6cf80d80-bbe6-11eb-89eb-861f6365724c.png)

After all that steps the binary is loaded:
![2021-05-23-164656_751x794_scrot](https://user-images.githubusercontent.com/673352/119265289-6f5a6780-bbe6-11eb-9ef6-7431b6364cb2.png)

I used the newest version of ghidra.
![2021-05-23-164758_493x106_scrot](https://user-images.githubusercontent.com/673352/119265324-9022bd00-bbe6-11eb-8f9b-3f65eddc9ca3.png)

What error do you get after fallowing these steps?

**Comment by ElijahBI** [comment]
So your guide is working up until I restart ghidra.

I download the zip for the Build for Ghidra 9.2.3 release and place it on my desk top, then I launch ghidra, go to file > install extensions, hit the + in the upper right, select your zip from my desktop and hit okay. At this point it shows up in the extensions list:
![1](https://user-images.githubusercontent.com/83904099/120134714-56c4f100-c194-11eb-88b6-ad001d15876e.png)
it will then ask me to restart:
![2](https://user-images.githubusercontent.com/83904099/120134742-66443a00-c194-11eb-9ee4-936284b35e5a.png)
but when I restart the extension will suddenly be missing from the extensions list:
![3](https://user-images.githubusercontent.com/83904099/120134778-79efa080-c194-11eb-98db-7b4dc458553d.png)

Here are my version numbers, I did note that I have a higher java version than you do in your image:
![4](https://user-images.githubusercontent.com/83904099/120134840-955aab80-c194-11eb-8cc9-ab63e0e8cd67.png)

**Comment by oshogbo** [comment]
Oh thats really weird. 
Did you check if ghidra core plugins are enabled?

**Comment by ElijahBI** [comment]
If the following is what you are referring to, yes it is enabled:

![1](https://user-images.githubusercontent.com/83904099/120916265-44ecbd80-c66e-11eb-95d8-4352af63167a.png)

**Comment by oshogbo** [comment]
To be honest I don't have much more idea why this disappeared.
What os are you using?

**Comment by madebr** [comment]
Deselecting the checkbox in front of the ghidra-lx-loader extension and clicking on OK, will remove the extension.
The `Install Extensions` dialog only shows the default extensions + those that are installed AND enabled.
